### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by abhinavsagar** [openai/gym-soccer#12]
I am getting the following error on installation.

` running install
    running build
    fatal: destination path 'hfo_py' already exists and is not an empty directory.
    Could not build hfo-py: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\WIN10~1\AppData\Local\Temp\pip-install-ogr72o6o\hfo-py\setup.py", line 31, in <module>
        include_package_data=True
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\WIN10~1\AppData\Local\Temp\pip-install-ogr72o6o\hfo-py\setup.py", line 13, in run
        subprocess.check_call(['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py'])
      File "c:\users\win 10\appdata\local\programs\python\python36\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128.
`

**Comment by mullachv** [comment]
I have a similar message when creating my own gym environment:
```
  ----------------------------------------
  Failed building wheel for hfo-py
  Running setup.py clean for hfo-py
Failed to build hfo-py
Installing collected packages: hfo-py, gym-shipping
  Running setup.py install for hfo-py ... error
    Complete output from command /Users/vmullachery/anaconda/envs/dl3.6/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/vh/pz0s55cx0_zfkk03n3c3sm4c0000gn/T/pip-install-0p5dvabd/hfo-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/vh/pz0s55cx0_zfkk03n3c3sm4c0000gn/T/pip-record-rrwjr0w7/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    fatal: destination path 'hfo_py' already exists and is not an empty directory.
    Could not build hfo-py: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vh/pz0s55cx0_zfkk03n3c3sm4c0000gn/T/pip-install-0p5dvabd/hfo-py/setup.py", line 31, in <module>
        include_package_data=True
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install.py", line 61, in run
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/vh/pz0s55cx0_zfkk03n3c3sm4c0000gn/T/pip-install-0p5dvabd/hfo-py/setup.py", line 13, in run
        subprocess.check_call(['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py'])
      File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128.
    

```

**Comment by MtPleast** [comment]
Same problem with you, have you guys solved it already?

**Comment by myl7** [comment]
No problem with me.

As for me, before the above error message, pip also reported that:

```
ERROR: Command errored out with exit status 1:
   command: /home/<user>/.conda/envs/pytorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x134jplm/hfo-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x134jplm/hfo-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u_k47fwb                                                   
       cwd: /tmp/pip-install-x134jplm/hfo-py/                                                                         
  Complete output (57 lines):                                                                                         
  running bdist_wheel                                                                                                 
  running build                                                                                                       
  Cloning into 'hfo_py'...                                                                                            
  CMake Warning:                                                                                                      
    No source or binary directory provided.  Both will be assumed to be the                                           
    same as the current working directory, but note that this warning will                                            
    become a fatal error in future CMake releases.                                                                    
                                                                                                                      
                                                                                                                      
  -- The C compiler identification is GNU 10.2.0                                                                      
  -- The CXX compiler identification is GNU 10.2.0                                                                    
  -- Detecting C compiler ABI info                                                                                    
  -- Detecting C compiler ABI info - done                                                                             
  -- Check for working C compiler: /usr/bin/cc - skipped                                                              
  -- Detecting C compile features                                                                                     
  -- Detecting C compile features - done                                                                              
  -- Detecting CXX compiler ABI info                                                                                  
  -- Detecting CXX compiler ABI info - done                                                                           
  -- Check for working CXX compiler: /usr/bin/c++ - skipped                                                           
  -- Detecting CXX compile features                                                                                   
  -- Detecting CXX compile features - done                                                                            
  -- Found Boost: /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake (found version "1.72.0") found components: system filesystem                                                                                                              
  -- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")                                                            
  -- Found FLEX: /usr/bin/flex (found version "2.6.4")                                                                
  CMake Error at /usr/share/cmake-3.18/Modules/FindQt4.cmake:1314 (message):                                          
    Found unsuitable Qt version "5.15.1" from /usr/bin/qmake, this code                                               
    requires Qt 4.x                                                                                                   
  Call Stack (most recent call first):                                                                                
    CMakeLists.txt:41 (find_package)                                                                                  
                                                                                                                      
                                                                                                                      
  -- Configuring incomplete, errors occurred!                                                                         
  See also "/tmp/pip-install-x134jplm/hfo-py/hfo_py/CMakeFiles/CMakeOutput.log".                                      
  Could not build hfo-py: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1..         
  Traceback (most recent call last):                                                                                  
    File "<string>", line 1, in <module>                                                                              
    File "/tmp/pip-install-x134jplm/hfo-py/setup.py", line 24, in <module>                                            
      setup(name='hfo-py',                                                                                            
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup       
      return distutils.core.setup(**attrs)                                                                            
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/distutils/core.py", line 148, in setup                          
      dist.run_commands()                                                                                             
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/distutils/dist.py", line 966, in run_commands                   
      self.run_command(cmd)                                                                                           
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command                    
      cmd_obj.run()                                                                                                   
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run           
      self.run_command('build')                                                                                       
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/distutils/cmd.py", line 313, in run_command                     
      self.distribution.run_command(command)                                                                          
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/distutils/dist.py", line 985, in run_command                    
      cmd_obj.run()                                                                                                   
    File "/tmp/pip-install-x134jplm/hfo-py/setup.py", line 14, in run                                                 
      subprocess.check_call(['cmake','-DCMAKE_BUILD_TYPE=Release'], cwd='hfo_py')                                     
    File "/home/<user>/.conda/envs/pytorch/lib/python3.8/subprocess.py", line 364, in check_call                         
      raise CalledProcessError(retcode, cmd)                                                                          
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.   
  ----------------------------------------                                                                            
  ERROR: Failed building wheel for hfo-py
```

means Qt4 is missing.

After installing Qt4, everything works well.
