### ISSUE TITLE
Problem with AgainstKeeper?

### ISSUE THREAD

**Issue by ikerrybtw** [openai/gym-soccer#3]
I am able to create instances of Soccer-v0 and SoccerEmptyGoal-v0 without any problem. But when I try to create an instance of SoccerAgainstKeeper-v0 by env = gym.make('SoccerAgainstKeeper-v0'), I get the following error message:

[2016-11-11 03:42:29,228] Making new env: SoccerAgainstKeeper-v0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aykan/gym/gym/envs/registration.py", line 130, in make
    return registry.make(id)
  File "/home/aykan/gym/gym/envs/registration.py", line 95, in make
    return spec.make()
  File "/home/aykan/gym/gym/envs/registration.py", line 70, in make
    cls = load(self._entry_point)
  File "/home/aykan/gym/gym/envs/registration.py", line 18, in load
    result = entry_point.load(False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'SoccerAgainstKeeperEnv'

Any idea why this might be the case? I want to work on this problem for a class project, so any input will be appreciated!

**Comment by ikerrybtw** [comment]
There was a typo in __init__.py, fixing it solves the problem.
