### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by quanvuong** [openai/gym-soccer#4]
`pip install gym-soccer` indicates that there's no matching package.

`pip install -e .` in the repo folder returns this error :(

```
Requirement already satisfied: gym>=0.2.3 in /Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages (from gym-soccer==0.0.1)
Collecting hfo_py>=0.2 (from gym-soccer==0.0.1)
  Using cached hfo-py-0.2.tar.gz
Requirement already satisfied: pyglet>=1.2.0 in /Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages (from gym>=0.2.3->gym-soccer==0.0.1)
Requirement already satisfied: six in /Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages (from gym>=0.2.3->gym-soccer==0.0.1)
Requirement already satisfied: requests>=2.0 in /Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages (from gym>=0.2.3->gym-soccer==0.0.1)
Requirement already satisfied: numpy>=1.10.4 in /Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages (from gym>=0.2.3->gym-soccer==0.0.1)
Building wheels for collected packages: hfo-py
  Running setup.py bdist_wheel for hfo-py ... error
  Complete output from command /Users/QV/code-project/learn/reinforcement_learning/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/tmpv_x4qxrgpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Cloning into 'hfo_py'...
  -- The C compiler identification is AppleClang 8.1.0.8020042
  -- The CXX compiler identification is AppleClang 8.1.0.8020042
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:765 (message):
    Imported targets not available for Boost version
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
    /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
    CMakeLists.txt:11 (find_package)


  CMake Warning at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:765 (message):
    Imported targets not available for Boost version
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:869 (_Boost_COMPONENT_DEPENDENCIES)
    /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:1472 (_Boost_MISSING_DEPENDENCIES)
    CMakeLists.txt:11 (find_package)


  CMake Error at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindBoost.cmake:1842 (message):
    Unable to find the requested Boost libraries.

    Unable to find the Boost header files.  Please set BOOST_ROOT to the root
    directory containing Boost or BOOST_INCLUDEDIR to the directory containing
    Boost's headers.
  Call Stack (most recent call first):
    CMakeLists.txt:11 (find_package)


  -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8")
  -- Found FLEX: /usr/bin/flex (found version "2.5.35")
  CMake Error at /usr/local/Cellar/cmake/3.8.1/share/cmake/Modules/FindQt4.cmake:1318 (message):
    Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
  Call Stack (most recent call first):
    CMakeLists.txt:41 (find_package)


  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  Boost_INCLUDE_DIR (ADVANCED)
     used as include directory in directory /private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/hfo_py
     used as include directory in directory /private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/hfo_py
     used as include directory in directory /private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/hfo_py
     used as include directory in directory /private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/hfo_py

  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/hfo_py/CMakeFiles/CMakeOutput.log".
  Could not build hfo-py: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py", line 31, in <module>
      include_package_data=True
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py", line 14, in run
      subprocess.check_call(['cmake','-DCMAKE_BUILD_TYPE=Release'], cwd='hfo_py')
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for hfo-py
  Running setup.py clean for hfo-py
Failed to build hfo-py
Installing collected packages: hfo-py, gym-soccer
  Running setup.py install for hfo-py ... error
    Complete output from command /Users/QV/code-project/learn/reinforcement_learning/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-ch7hup6a-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/QV/code-project/learn/reinforcement_learning/venv/bin/../include/site/python3.5/hfo-py:
    running install
    running build
    fatal: destination path 'hfo_py' already exists and is not an empty directory.
    Could not build hfo-py: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py", line 31, in <module>
        include_package_data=True
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/QV/code-project/learn/reinforcement_learning/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py", line 13, in run
        subprocess.check_call(['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/LARG/HFO.git', 'hfo_py']' returned non-zero exit status 128

    ----------------------------------------
Command "/Users/QV/code-project/learn/reinforcement_learning/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-ch7hup6a-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/QV/code-project/learn/reinforcement_learning/venv/bin/../include/site/python3.5/hfo-py" failed with error code 1 in /private/var/folders/w4/3w7fvl4n4sqdzt2d49qj9p1c0000gn/T/pip-build-db1mrcg4/hfo-py/
```

**Comment by quanvuong** [comment]
I installed Qt and [HFO](https://github.com/LARG/HFO)'s installation and sample examples ran fine ...

**Comment by Lonely-wind** [comment]
Hello, do you find any solutions for this issue at last? @quanvuong

**Comment by rubensolozabal** [comment]
Verify you have installed Qt4.x and that it is selected using the comman:
 qtchooser -print-env
One its done, go to HFO repository and follow the installation steps. It worked for me.

**Comment by stevenwernercs** [comment]
> ```
> Collecting hfo_py>=0.2 (from gym-soccer==0.0.1)
>   Using cached hfo-py-0.2.tar.gz
> 
> ```

The issue is installing the `hfo-py` dependency.  

Try `pip install hfo-py`, should get same error. So you need to identify why that didnt install. 

I was missing many things. On mac I had to install cmake, qt, & boost. Then I could install the hfo-py
`brew install cmake`
`brew install qt`
`brew install boost`
